import fs from 'fs';

const playlist = [
  { title: "Lag Ja Gale", artist: "Lata Mangeshkar", id: "TFr6G5zveIo" },
  { title: "Tujhe Dekha Toh Ye Jaana Sanam", artist: "Kumar Sanu & Lata", id: "e3bMCABpbJc" },
  { title: "Kal Ho Naa Ho", artist: "Sonu Nigam", id: "g0eO74UmRBs" },
  { title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh", id: "YOYN9qNXmAw" },
  { title: "Tum Hi Ho", artist: "Arijit Singh", id: "IJq0yyWug1k" },
  { title: "Kun Faya Kun", artist: "A.R. Rahman", id: "T94PHkuydcw" },
  { title: "Kabira", artist: "Arijit Singh & Tochi Raina", id: "jHNNMj5bNQw" },
  { title: "Ek Ladki Ko Dekha Toh", artist: "Kumar Sanu", id: "V1cDBjVqMC0" },
  { title: "Dil To Pagal Hai", artist: "Lata & Udit Narayan", id: "wJOD3QBRTVU" },
  { title: "Mere Sapno Ki Rani", artist: "Kishore Kumar", id: "EjPVSmNsjFw" },
  { title: "Dum Maro Dum", artist: "Asha Bhosle", id: "V0lK4BSEJAQ" },
  { title: "Roop Tera Mastana", artist: "Kishore Kumar", id: "2JhZnrE-dPU" },
  { title: "Yeh Dosti", artist: "Kishore Kumar & Manna Dey", id: "d2WVaGQzCRU" },
  { title: "Jai Ho", artist: "A.R. Rahman", id: "xwwAVRyNmgQ" },
  { title: "Tere Bina Zindagi Se", artist: "Lata & Kishore", id: "BKiV-bAsITU" },
  { title: "Kuch Kuch Hota Hai", artist: "Udit Narayan & Alka", id: "aCJbXnIPaXk" },
  { title: "Chura Liya Hai Tumne", artist: "Asha Bhosle & Mohd Rafi", id: "QBl3QmHJut0" },
  { title: "Pehla Nasha", artist: "Udit Narayan & Sadhana", id: "FjCDbEbGgJk" },
  { title: "Dil Chahta Hai", artist: "Shankar Mahadevan", id: "BPA0prCz_Gg" },
  { title: "Pyar Deewana Hota Hai", artist: "Kishore Kumar", id: "JqEbmXJpOYA" },
  { title: "O Mere Dil Ke Chain", artist: "Kishore Kumar", id: "kf0UxH8Okro" },
  { title: "Pal Pal Dil Ke Paas", artist: "Kishore Kumar", id: "A_JVPm0M3x0" },
  { title: "Gulabi Aankhen", artist: "Mohammed Rafi", id: "Bp8E6VgWNHE" },
  { title: "Main Shayar To Nahin", artist: "Shailendra Singh", id: "Y4JRTL_nFJM" },
  { title: "Zindagi Ek Safar", artist: "Kishore Kumar", id: "OYS-a1Xfbp4" },
  { title: "Tumse Milke Dil Ka", artist: "Kumar Sanu", id: "5vIwMgbVjJo" },
  { title: "Ye Kaali Kaali Aankhen", artist: "Kumar Sanu", id: "MQ5MFw-TJIA" },
  { title: "Saanson Ki Zaroorat", artist: "Kumar Sanu", id: "Y1-bRJtVjTI" },
  { title: "Bahon Mein Chale Aao", artist: "Lata Mangeshkar", id: "EFWe-2ys_7c" },
  { title: "Mera Joota Hai Japani", artist: "Mukesh", id: "hAb_v7eaCrI" },
  { title: "Yeh Raat Bheegi Bheegi", artist: "Lata & Manna Dey", id: "UhJVJijrLaY" },
  { title: "Suraj Hua Maddham", artist: "Sonu Nigam & Alka", id: "qfHamAI78OE" },
  { title: "Mitwa", artist: "Shafqat Amanat Ali", id: "DpQ6bwmLfNg" },
  { title: "Tu Hi Re", artist: "Hariharan", id: "X2EkNPV9fXI" },
  { title: "Dil Se Re", artist: "A.R. Rahman", id: "ixDeADMYjRg" },
  { title: "Rang De Basanti", artist: "Daler Mehndi & A.R.R.", id: "ry7Uwi-GunM" },
  { title: "Sandese Aate Hain", artist: "Sonu Nigam & Roop Kumar", id: "B3f7jOZYaM0" },
  { title: "Ae Watan", artist: "Arijit Singh", id: "2GfiRVRHYvs" },
  { title: "Chak De India", artist: "Sukhwinder Singh", id: "3rKH-vOwR28" },
  { title: "Papa Kehte Hain", artist: "Udit Narayan", id: "h0k4dOIf2KI" },
  { title: "Tadap Tadap", artist: "KK", id: "ZfIbIJBrnsA" },
  { title: "Dhoom Machale", artist: "Sunidhi Chauhan", id: "vGTr-MAb6rs" },
  { title: "Zara Zara Behekta Hai", artist: "Bombay Jayashri", id: "9u0LfOKz6Rg" },
  { title: "Ajeeb Dastan Hai Yeh", artist: "Lata Mangeshkar", id: "0s4L5l3UJDg" },
  { title: "Abhi Mujh Mein Kahin", artist: "Sonu Nigam", id: "LNS6OGHJ5vU" },
  { title: "Tere Naam", artist: "Udit Narayan", id: "4kT6v0VOqz0" },
  { title: "Sun Raha Hai Na Tu", artist: "Arijit Singh", id: "rUqq6R6kOA0" },
  { title: "Chahun Main Ya Naa", artist: "Arijit Singh & Palak", id: "9AVcFJTNdb4" },
  { title: "Galliyan", artist: "Ankit Tiwari", id: "jG_gy5rC3jY" },
  { title: "Ilahi", artist: "Arijit Singh", id: "RxOgPVtnxhI" },
  { title: "Muskurane", artist: "Arijit Singh", id: "qJlJrUGmXtE" },
  { title: "Soch Na Sake", artist: "Arijit Singh", id: "vB7j2mhz2Zo" },
  { title: "Ae Dil Hai Mushkil", artist: "Arijit Singh", id: "6FURuLYrR_Q" },
  { title: "Bulleya", artist: "Amit Mishra & Shilpa", id: "gy49O1wqsI4" },
  { title: "Channa Mereya", artist: "Arijit Singh", id: "284Ov7yFfnE" },
  { title: "Aaj Jaane Ki Zid Na Karo", artist: "Farida Khanum", id: "THnNPRcR5Uc" },
  { title: "Kya Hua Tera Vaada", artist: "Mohammed Rafi", id: "VNaqVbbBYgg" },
  { title: "Agar Tum Saath Ho", artist: "Arijit & Alka", id: "sK2FNBsmHiA" },
  { title: "Gerua", artist: "Arijit Singh & Antara", id: "AEId0jZ5BaY" },
  { title: "Janam Janam", artist: "Arijit Singh & Antara", id: "F55bMaBglic" },
  { title: "Samjhawan", artist: "Arijit Singh & Shreya", id: "WPniKGKMuHg" },
  { title: "Humdard", artist: "Arijit Singh", id: "HYEuSiKYmFQ" },
  { title: "Tere Bina", artist: "A.R. Rahman", id: "1e3xK7PB-pw" },
  { title: "Enna Sona", artist: "Arijit Singh", id: "sHGP8YADfH8" },
  { title: "Hawayein", artist: "Arijit Singh", id: "cYOB941gyXI" },
  { title: "Main Rang Sharbaton Ka", artist: "Arijit Singh & Chinmayi", id: "D5L07Jp84nk" },
  { title: "Pani Da Rang", artist: "Ayushmann Khurrana", id: "ckixjbMhkYQ" },
  { title: "Dheere Dheere Se", artist: "Kumar Sanu & Anuradha", id: "jOfsPpKxZBI" },
  { title: "Jaadu Teri Nazar", artist: "Udit Narayan", id: "CChGXSMonHQ" },
  { title: "Mera Dil Bhi Kitna Pagal", artist: "Kumar Sanu & Alka", id: "JlPAFexJWMQ" },
  { title: "Do Dil Mil Rahe Hain", artist: "Kumar Sanu", id: "cfr5VOvnyKg" },
  { title: "Baazigar O Baazigar", artist: "Kumar Sanu & Alka", id: "L6Yj-Cj0EgE" },
  { title: "Bahut Pyar Karte Hain", artist: "Anuradha Paudwal", id: "02epB67mg_0" },
  { title: "Chand Sifarish", artist: "Shaan", id: "fF7e57F1EYM" },
  { title: "O Saathi Re", artist: "Kishore Kumar", id: "C_X-X_QiStE" },
  { title: "Bheegi Bheegi Raaton Mein", artist: "Adnan Sami", id: "Gu_FMrP0HJ4" },
  { title: "Barso Re Megha", artist: "Shreya Ghoshal", id: "3Y0IF6F48h0" },
  { title: "Woh Lamhe", artist: "Atif Aslam", id: "zQEabHJCAWE" },
  { title: "Aadat", artist: "Atif Aslam", id: "FqJVDrjDc10" },
  { title: "Pehli Nazar Mein", artist: "Atif Aslam", id: "BadBAMnPX0I" },
  { title: "Tere Sang Yaara", artist: "Atif Aslam", id: "9IOV4ZSfJJM" },
  { title: "Jeena Jeena", artist: "Atif Aslam", id: "bvGFrL4RLsY" },
  { title: "Dil Diyan Gallan", artist: "Atif Aslam", id: "SAcpESN_Fk4" },
  { title: "Phir Mohabbat", artist: "Arijit Singh", id: "WXF07QoF5B0" },
  { title: "Hamari Adhuri Kahani", artist: "Arijit Singh", id: "X3IijSvG4M8" },
  { title: "Lambiyaan Si Judaiyaan", artist: "Arijit Singh", id: "UcNgFOQ_QSE" },
  { title: "Sanam Re", artist: "Arijit Singh", id: "9gRzjPML-b8" },
  { title: "Baatein Ye Kabhi Na", artist: "Arijit Singh", id: "I5a50djPkdQ" },
  { title: "Teri Deewani", artist: "Kailash Kher", id: "LycnVYCgRKI" },
  { title: "Allah Ke Bande", artist: "Kailash Kher", id: "DpLdUAjhMcE" },
  { title: "Roobaroo", artist: "A.R. Rahman", id: "TDwNMBJVLIQ" },
  { title: "Khwaja Mere Khwaja", artist: "A.R. Rahman", id: "XLNwRPMhYnI" },
  { title: "Tujhme Rab Dikhta Hai", artist: "Roop Kumar Rathod", id: "bvGCH14jUfE" },
  { title: "Sajdaa", artist: "Rahat Fateh Ali Khan", id: "V1M_JzQWBLI" },
  { title: "Pee Loon", artist: "Mohit Chauhan", id: "UqU9rBLyEWo" },
  { title: "Masakali", artist: "Mohit Chauhan", id: "PS9u5FPkmQg" },
  { title: "Tum Se Hi", artist: "Mohit Chauhan", id: "mt9xg0JGbKg" },
  { title: "Sadda Haq", artist: "Mohit Chauhan", id: "yVuKjQfS2og" },
  { title: "Khairiyat", artist: "Arijit Singh", id: "hoNb6HuNmU0" },
  { title: "Shayad", artist: "Arijit Singh", id: "R_5KB5S3dys" },
  { title: "Nashe Si Chadh Gayi", artist: "Arijit Singh", id: "Wd2B8OAotU8" },
  { title: "Kala Chashma", artist: "Badshah & Amar Arshi", id: "k4yXQPm2hSs" },
  { title: "Ainvayi Ainvayi", artist: "Salim Merchant", id: "ILJtPYwr6Cg" },
  { title: "London Thumakda", artist: "Labh Janjua & Sonu", id: "udra3Mfw2oo" },
  { title: "Nagada Sang Dhol", artist: "Shreya & Osman Mir", id: "F1nOFiDv3IE" },
  { title: "Chalte Chalte", artist: "Lata Mangeshkar", id: "wfkOCztE5gM" },
  { title: "Koi Fariyaad", artist: "Jagjit Singh", id: "oqIZ7vM0BBw" },
  { title: "Hothon Se Chhulo Tum", artist: "Jagjit Singh", id: "gkM1bmvXUFE" },
  { title: "Chithi Na Koi Sandesh", artist: "Jagjit Singh", id: "V46o7BKUFT0" },
  { title: "Badan Pe Sitare", artist: "Mohammed Rafi", id: "PZpxuRx88CU" },
  { title: "Likhe Jo Khat Tujhe", artist: "Mohammed Rafi", id: "6pvLjIm7JEk" },
  { title: "Hume Tumse Pyaar Kitna", artist: "Kishore Kumar", id: "kkPdrCF4fcs" },
  { title: "Rim Jhim Gire Saawan", artist: "Kishore Kumar & Lata", id: "4laqJlEBi-s" },
  { title: "Kabhi Kabhie Mere Dil", artist: "Mukesh & Lata", id: "Mzj6vxsBPBg" },
  { title: "Yeh Sham Mastani", artist: "Kishore Kumar", id: "s2HJJl4rF4w" },
  { title: "Ek Ajnabee Haseena Se", artist: "Kishore Kumar", id: "FVHnFFX6w_0" },
  { title: "Bekhayali", artist: "Sachet Tandon", id: "VOLkIDqtPJA" },
  { title: "Lut Gaye", artist: "Jubin Nautiyal", id: "o9GksBv_nCA" },
  { title: "Raataan Lambiyan", artist: "Jubin & Asees Kaur", id: "gvyUuxMaBwk" },
  { title: "Kesariya", artist: "Arijit Singh", id: "BddP6PYo2gs" },
  { title: "Pasoori", artist: "Ali Sethi & Shae Gill", id: "5Eqb_-j3FDA" },
  { title: "Apna Bana Le", artist: "Arijit Singh", id: "v1LxGCmHRl0" },
  { title: "Tera Chehra", artist: "Adnan Sami", id: "y7RCq1y3w4o" },
  { title: "Kabhi To Nazar Milao", artist: "Adnan Sami & Asha", id: "b3GxkHKeCho" },
  { title: "Dil Ibaadat", artist: "KK", id: "ooMTxL1wfLY" },
  { title: "Aankhon Mein Teri", artist: "KK", id: "N2QCVL_v7CY" },
  { title: "Kya Mujhe Pyaar Hai", artist: "KK", id: "9FqWHnwPlrA" },
  { title: "Ajab Si", artist: "KK", id: "mvj8F-pnEfk" },
  { title: "Badtameez Dil", artist: "Benny Dayal", id: "II2EO3Nw4Q0" },
  { title: "Balam Pichkari", artist: "Vishal & Shalmali", id: "0WtRNGubWGA" },
  { title: "Kajra Re", artist: "Alisha Chinai & Shankar", id: "LW6bHHEjpMo" },
  { title: "Desi Girl", artist: "Sunidhi & Shankar", id: "v4GpSGeCxBA" },
  { title: "Sheila Ki Jawani", artist: "Sunidhi Chauhan", id: "ZTmF2v59CtI" },
  { title: "Give Me Some Sunshine", artist: "Suraj Jagan", id: "bSqkACTFaEo" },
  { title: "All Izz Well", artist: "Sonu Nigam", id: "4pj4MBJivj4" },
  { title: "Behti Hawa Sa", artist: "Shaan", id: "NwGOaJdW5KI" },
  { title: "Tere Liye (Veer Zaara)", artist: "Lata & Roop Kumar", id: "mYUGeIOTxfE" },
  { title: "Kaho Na Pyaar Hai", artist: "Udit & Alka", id: "rI-9gGOSAh8" },
  { title: "Humko Humise Chura Lo", artist: "Udit & Alka", id: "XFFLz4GfVcM" },
  { title: "Ve Maahi", artist: "Arijit Singh & Asees", id: "LFfldP_g_hE" },
  { title: "Jab Koi Baat Bigad Jaye", artist: "Kumar Sanu", id: "sDNqWpN3m8c" },
  { title: "Chura Ke Dil Mera", artist: "Kumar Sanu & Alka", id: "pJJmBcT0V2o" },
  { title: "Na Tum Jaano Na Hum", artist: "Lucky Ali", id: "nqVhHiUfbgI" },
  { title: "O Sanam", artist: "Lucky Ali", id: "bDK00FRImhQ" },
  { title: "Sapnon Se Bhare Naina", artist: "Shankar Mahadevan", id: "LCTG3nfrCgI" },
  { title: "Sun Saathiya", artist: "Priya Saraiya", id: "X2_Nq7Tbpjk" },
  { title: "Sooraj Dooba Hain", artist: "Arijit Singh", id: "RzVAQ_3-WAU" },
  { title: "Mast Magan", artist: "Arijit Singh", id: "RWuIjkCQBHU" },
  { title: "Ishq Wala Love", artist: "Neeti Mohan & Salim", id: "MJXH1kZiLmA" },
  { title: "Manwa Laage", artist: "Shreya & Arijit", id: "AIJKH3UBFss" },
  { title: "Chunar", artist: "Arijit Singh", id: "XHV_vwBWyT8" },
  { title: "Naina", artist: "Neeti Mohan", id: "ELv-foVKhqk" },
  { title: "Saibo", artist: "Shreya & Tochi Raina", id: "1_o90bwxJgk" },
  { title: "Bade Achhe Lagte Hain", artist: "Amit Kumar", id: "9g5mJ5K4qds" },
  { title: "Mere Rang Mein", artist: "S.P. Balasubrahmanyam", id: "VK6_tjkgGQE" },
  { title: "Gaata Rahe Mera Dil", artist: "Kishore Kumar & Lata", id: "5LCif9yiCq0" },
  { title: "Aa Chal Ke Tujhe", artist: "Kishore Kumar", id: "c2YyL-4d_2I" },
  { title: "Ek Pyar Ka Nagma Hai", artist: "Lata & Mukesh", id: "YQ18RVy0r8o" },
  { title: "Abhi Na Jao Chhod Kar", artist: "Asha & Rafi", id: "c6FPxPJHnVI" },
  { title: "Aap Ki Nazron Ne Samjha", artist: "Lata Mangeshkar", id: "dkGxXbO3daA" },
  { title: "Ek Ladki Bheegi Bhagi", artist: "Kishore Kumar", id: "L_Upo3QSXwY" },
  { title: "Pyaar Kiya To Darna Kya", artist: "Lata Mangeshkar", id: "bBwGJHHXI68" },
];

async function checkEmbeddable(id) {
  try {
    const res = await fetch(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${id}&format=json`);
    return res.status === 200;
  } catch (e) {
    return false;
  }
}

async function run() {
  console.log(`Checking ${playlist.length} songs...`);
  const valid = [];
  for (let i = 0; i < playlist.length; i++) {
    const track = playlist[i];
    const ok = await checkEmbeddable(track.id);
    if (ok) {
      valid.push(track);
    }
  }
  console.log(`Valid: ${valid.length}/${playlist.length}`);
  fs.writeFileSync('valid_playlist.json', JSON.stringify(valid, null, 2));
}

run();
