import "./globals.css";

export const viewport = {
  themeColor: "#1a1208",
};

export const metadata = {
  title: "Max Salon | Deluxe Saloon — An ambient street-corner radio",
  description:
    "Pull up a chair at Max Salon (Deluxe Saloon): a always-on radio playing old-school favourites over an illustrated Indian street corner. Experience a red street-side barbershop in India with continuous Truck Driver songs, vintage Hindi music, and classic Bollywood hits.",
  keywords: [
    "max salon",
    "salon song",
    "Deluxe Saloon: a always-on radio playing old-school favourites over an illustrated Indian street corner",
    "a red street-side barbershop in India",
    "a barber",
    "Deluxe Saloon",
    "Truck Driver songs",
    "old hindi songs",
    "ambient radio",
    "bollywood classics",
    "90s romantic songs",
    "retro hindi music",
    "Sharma ji ka salon",
    "indian barbershop radio",
    "vintage hindi playlist",
    "continuous hindi music",
    "lata mangeshkar kishore kumar hits",
    "hindi ghazals",
    "indian street corner aesthetic",
    "hindi lofi songs for studying",
    "90s bollywood lofi radio live",
    "old hindi songs instrumental for work",
    "relaxing hindi music for sleep",
    "aesthetic indian lofi background music",
    "old hindi songs with rain sounds",
    "late night drive hindi songs",
    "indian street ambiance with music",
    "barber shop radio aesthetic",
    "retro bollywood cassette songs",
    "90s hindi romantic songs continuous play",
    "lata mangeshkar kishore kumar hit songs",
    "evergreen old hindi songs radio",
    "truck driver hindi songs playlist",
    "best hindi ghazals of all time",
    "hindi ghazals background music",
    "90s romantic songs playing in a barber shop",
    "background ambiance for studying rainy Sunday hindi",
    "deluxe saloon barber shop radio",
    "max salon old songs",
    "old hindi songs",
    "old hindi songs radio",
    "old hindi songs live",
    "old hindi songs nonstop",
    "old hindi songs 24/7",
    "evergreen hindi songs",
    "evergreen old hindi songs",
    "old is gold hindi songs",
    "retro hindi songs",
    "retro bollywood songs",
    "classic hindi songs",
    "classic bollywood songs",
    "hindi retro radio",
    "bollywood retro radio",
    "old bollywood songs",
    "old bollywood songs radio",
    "old bollywood songs nonstop",
    "hindi songs radio",
    "hindi music radio",
    "indian music radio",
    "90s hindi songs",
    "90s bollywood songs",
    "90s bollywood hits",
    "90s hindi songs nonstop",
    "90s hindi songs radio",
    "90s bollywood radio",
    "90s bollywood hits radio",
    "90s romantic songs",
    "90s romantic hindi songs",
    "90s romantic bollywood songs",
    "90s love songs hindi",
    "90s evergreen hindi songs",
    "90s old hindi songs",
    "90s nostalgia songs",
    "90s nostalgia hindi",
    "90s bollywood nostalgia",
    "90s hindi songs continuous",
    "90s hindi songs live",
    "90s bollywood songs live",
    "90s bollywood playlist",
    "90s hindi playlist",
    "90s hindi jukebox",
    "hindi lofi songs",
    "bollywood lofi",
    "hindi lofi radio",
    "90s hindi lofi",
    "90s bollywood lofi",
    "old hindi songs lofi",
    "retro hindi lofi",
    "retro bollywood lofi",
    "90s romantic lofi",
    "hindi lofi mix",
    "bollywood lofi mix",
    "old bollywood lofi",
    "lofi hindi songs for studying",
    "lofi hindi songs for sleep",
    "relaxing hindi lofi",
    "hindi lofi chill",
    "hindi lofi background music",
    "aesthetic hindi lofi",
    "indian lofi radio",
    "indian lofi music",
    "slow reverb hindi songs",
    "90s hindi slow reverb",
    "old hindi songs slow reverb",
    "bollywood slow reverb",
    "hindi ambient radio",
    "indian ambient radio",
    "retro ambient radio",
    "bollywood ambient music",
    "hindi background music",
    "old hindi background music",
    "bollywood background music",
    "hindi music for studying",
    "hindi music for work",
    "hindi music for relaxing",
    "hindi music for sleep",
    "hindi music for reading",
    "hindi music for cafe",
    "hindi music for driving",
    "relaxing hindi music",
    "calm hindi music",
    "peaceful hindi songs",
    "soothing hindi songs",
    "nostalgic hindi music",
    "nostalgic bollywood radio",
    "old hindi songs with rain",
    "hindi songs with rain sounds",
    "90s hindi songs rain",
    "90s romantic songs rain",
    "bollywood rain songs",
    "hindi rain ambience",
    "rainy night hindi songs",
    "rainy evening hindi songs",
    "rain sounds hindi songs",
    "rain and old hindi songs",
    "monsoon hindi songs",
    "monsoon bollywood songs",
    "retro hindi monsoon songs",
    "old hindi songs rainy night",
    "90s bollywood rainy night",
    "hindi lofi rain",
    "bollywood lofi rain",
    "rainy cafe hindi music",
    "rainy street hindi music",
    "indian barber shop",
    "indian barbershop",
    "indian barber shop radio",
    "indian barber shop music",
    "barber shop radio",
    "barber shop music",
    "barber shop ambience",
    "barber shop aesthetic",
    "indian street aesthetic",
    "indian street corner",
    "indian street ambience",
    "indian street radio",
    "old indian barber shop",
    "retro indian barber shop",
    "desi barber shop",
    "desi barber shop aesthetic",
    "small town barber shop india",
    "indian salon ambience",
    "indian salon radio",
    "salon radio india",
    "barber radio india",
    "old school barber shop",
    "vintage barber shop india",
    "retro salon india",
    "Sharma Ji Ka Salon",
    "Sharma Ji Salon",
    "Sharma Ji Ki Dukaan",
    "Sharma Ji Barber Shop",
    "Sharma Ji Ka Barber Shop",
    "Sharma Ji Salon Radio",
    "Sharma Ji Radio",
    "Desi Salon Radio",
    "Desi Barber Radio",
    "Indian Street Barber Radio",
    "24/7 hindi radio",
    "24/7 hindi music",
    "24/7 bollywood radio",
    "24/7 old hindi songs",
    "24/7 retro hindi music",
    "24/7 retro bollywood",
    "nonstop hindi songs",
    "nonstop old hindi songs",
    "nonstop bollywood songs",
    "continuous hindi music",
    "continuous hindi songs",
    "continuous bollywood songs",
    "hindi songs nonstop live",
    "old hindi songs nonstop live",
    "retro hindi radio live",
    "bollywood radio live",
    "old hindi radio live",
    "hindi radio online",
    "old hindi radio online",
    "retro radio online",
    "truck driver songs",
    "truck driver hindi songs",
    "truck songs hindi",
    "truck mein bajne wale gaane",
    "truck songs",
    "highway songs hindi",
    "highway hindi songs",
    "road trip hindi songs",
    "long drive hindi songs",
    "long drive bollywood songs",
    "driving songs hindi",
    "night drive hindi songs",
    "highway radio hindi",
    "truck radio hindi",
    "desi truck songs",
    "truck driver playlist",
    "truck driver playlist hindi",
    "90s truck songs",
    "90s truck driver songs",
    "old hindi truck songs",
    "truck songs nonstop",
    "highway songs nonstop",
    "road trip radio hindi",
    "hindi ghazals",
    "best hindi ghazals",
    "old hindi ghazals",
    "old ghazals",
    "ghazal radio",
    "ghazal radio live",
    "ghazals online",
    "hindi ghazal radio",
    "ghazal background music",
    "relaxing ghazals",
    "romantic ghazals",
    "ghazals for late night",
    "ghazals for sleep",
    "ghazals for studying",
    "classic hindi ghazals",
    "evergreen ghazals",
    "90s ghazals",
    "retro ghazals",
    "sad ghazals",
    "late night ghazal radio",
    "Lata Mangeshkar songs",
    "Lata Mangeshkar hits",
    "Lata Mangeshkar old songs",
    "Kishore Kumar songs",
    "Kishore Kumar hits",
    "Kishore Kumar old songs",
    "Mohammed Rafi songs",
    "Mohammed Rafi hits",
    "Asha Bhosle songs",
    "Mukesh songs",
    "R.D. Burman songs",
    "Kumar Sanu songs",
    "Kumar Sanu 90s hits",
    "Alka Yagnik songs",
    "Udit Narayan songs",
    "90s Kumar Sanu songs",
    "90s Alka Yagnik songs",
    "90s Udit Narayan songs",
    "Lata Kishore songs",
    "Lata Mangeshkar Kishore Kumar hits",
    "Kumar Sanu Alka Yagnik hits",
    "hindi songs for relaxation",
    "hindi songs for sleep",
    "hindi songs for studying",
    "hindi songs for working",
    "hindi songs for reading",
    "hindi songs for driving",
    "hindi songs for late night",
    "hindi songs for rainy night",
    "hindi songs for peaceful evening",
    "hindi songs for nostalgia",
    "hindi songs for chai",
    "hindi songs for weekend",
    "hindi songs for background",
    "hindi songs for cafe",
    "hindi songs for travel",
    "old hindi songs for relaxation",
    "old hindi songs for sleep",
    "old hindi songs for studying",
    "90s songs for relaxation",
    "90s songs for late night",
    "90s songs for driving",
    "late night barber shop",
    "late night indian street",
    "indian street at night",
    "indian street corner radio",
    "rainy indian street",
    "rainy barber shop",
    "rainy salon ambience",
    "small town india ambience",
    "indian town ambience",
    "old india ambience",
    "90s india ambience",
    "90s indian street",
    "1990s india aesthetic",
    "retro india aesthetic",
    "old school india aesthetic",
    "indian nostalgia ambience",
    "desi nostalgia ambience",
    "chai shop radio",
    "chai tapri radio",
    "indian tea stall radio",
    "street corner radio india",
    "90s hindi songs playing in a barber shop",
    "old hindi songs playing in a barber shop",
    "90s bollywood radio barber shop",
    "indian barber shop radio",
    "old hindi songs barber shop",
    "retro hindi barber shop",
    "90s songs at indian barber shop",
    "indian street corner radio",
    "old hindi songs indian street ambience",
    "90s bollywood indian street ambience",
    "retro bollywood street radio",
    "sharma ji ka salon radio",
    "sharma ji ka salon old songs",
    "desi barber shop radio",
    "indian salon old songs",
    "old school indian barber shop radio",
    "90s hindi songs continuous play",
    "90s bollywood continuous radio",
    "old hindi songs continuous radio",
    "retro hindi music 24/7",
    "90s bollywood radio 24/7",
    "old hindi songs radio 24/7",
    "rainy indian barber shop radio",
    "late night barber shop radio",
    "indian street radio old hindi songs"
  ],
  authors: [{ name: "Max Salon" }],
  alternates: {
    canonical: "https://maxsalon.moneycal.in",
  },
  icons: {
    icon: "/icon.svg",
    apple: "/icon.svg",
  },
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title: "Max Salon | Deluxe Saloon — An ambient street-corner radio",
    description:
      "Pull up a chair at Max Salon (Deluxe Saloon): a always-on radio playing old-school favourites over an illustrated Indian street corner.",
    url: "https://maxsalon.moneycal.in",
    type: "website",
    images: [
      {
        url: "/backdrop.png",
        width: 1920,
        height: 1088,
        alt: "Max Salon Background",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Max Salon | Deluxe Saloon",
    description:
      "A red street-side barbershop in India. An always-on radio playing old-school Hindi favourites at Max Salon.",
    images: ["/backdrop.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link rel="preload" as="image" href="/backdrop.png" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "RadioStation",
              "name": "Max Salon Radio",
              "alternateName": "Deluxe Saloon",
              "url": "https://maxsalon.moneycal.in",
              "description": "An always-on internet radio playing old-school 90s Hindi film songs and retro Indian music over an ambient street-corner background.",
              "genre": ["Retro Hindi Music", "90s Bollywood", "Lofi"],
              "image": "https://maxsalon.moneycal.in/backdrop.png"
            })
          }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
